# Thanks for usingDrop.
# For bug report or suggestion, join https://discord.gg/fV4P2yMSgR

# If Player.Require-Permission = true, player with "headdrop.player" permission will drop head on death.
# Config.Require-Killer-Player = true means Killer need to be player to drop killed mob.
# If Config.Killer-Require-Permission = true, Player need "headdrop.killer" permission to let entity drop on death.
# Chances will be ignored if you disable drop.
# Chance is from 1-100. you can use fraction number too.

# {KILLER} will return player name who killed the mob, {MOB} will return mob name which was killed (only work on Bot section)

# add a blank line ("") if you want to disable lore.

Config:
  Version: ${project.version}
  Update-Notify: true
  Require-Killer-Player: true
  Require-Charged-Creeper: false
  Killer-Require-Permission: false
  Enable-Looting: true
  Baby-HeadDrop: true
  Enable-Perm-Chance: false
  Disable-Worlds:
    - demoWorld
    - demoWorld2

Database:
  Online: true
  URL: "jdbc:sqlite:HeadDrop.sqlite"
  User:
  Password:

Web:
  Enable: false
  Port: 8080
  Endpoint: "leaderboard" #make the website address https://localhost:8080/leaderboard

Bot:
  Enable: false
  WebHook: ""
  Title: "HeadDrop"
  Description: "{KILLER} killed {MOB} and got a head!"
  Footer: "HeadDrop by RRS"

PLAYER:
  Drop: true
  Chance: 100
  Require-Permission: false
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ZOMBIE:
  Name: "Zombie"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

WITHER_SKELETON:
  Name: "Wither Skeleton"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

CREEPER:
  Name: "Creeper"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SKELETON:
  Name: "Skeleton"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

AXOLOTL:
  Name: "Axolotl"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

BAT:
  Name: "Bat"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

BEE:
  Name: "Bee"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

BLAZE:
  Name: "Blaze"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

CAT:
  Name: "Cat"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

DOLPHIN:
  Name: "Dolphin"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

DROWNED:
  Name: "Drowned"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SPIDER:
  Name: "Spider"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"
CAVE_SPIDER:
  Name: "Cave Spider"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

CHICKEN:
  Name: "Chicken"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ENDERMAN:
  Name: "EnderMan"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

COW:
  Name: "Cow"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ENDERMITE:
  Name: "EnderMite"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

EVOKER:
  Name: "Evoker"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

DONKEY:
  Name: "Donkey"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

FOX:
  Name: "Fox"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SHEEP:
    Name: "Sheep"
    Drop: true
    Chance: 100
    Lore:
      - "Killed by {KILLER}"
      - "Killed on {DATE}"

GIANT:
  Name: "Giant"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

HOGLIN:
  Name: "Hoglin"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

HUSK:
  Name: "Husk"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

GOAT:
  Name: "Goat"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

IRON_GOLEM:
  Name: "Iron Golem"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ILLUSIONER:
  Name: "Illusioner"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

HORSE:
  Name: "Horse"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

GUARDIAN:
  Name: "Guardian"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

MUSHROOM_COW:
  Name: "Mushroom Cow"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

OCELOT:
  Name: "Ocelot"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

PHANTOM:
  Name: "Phantom"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

GLOW_SQUID:
  Name: "Glow Squid"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

PIG:
  Name: "Pig"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

LLAMA:
  Name: "LLAMA"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

MULE:
  Name: "Mule"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

PIGLIN:
  Name: "Piglin"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

PIGLIN_BRUTE:
  Name: "Piglin Brute"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ELDER_GUARDIAN:
  Name: "Elder Guardian"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

PUFFERFISH:
  Name: "Puffer Fish"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SILVERFISH:
  Name: "Silver Fish"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

POLAR_BEAR:
  Name: "Polar Bear"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SALMON:
  Name: "Salmon"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SHULKER:
  Name: "Shulker"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

STRAY:
  Name: "Stray"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

STRIDER:
  Name: "Strider"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SKELETON_HORSE:
  Name: "Skeleton Horse"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

PILLAGER:
  Name: "Pillager"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SQUID:
  Name: "Squid"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

WANDERING_TRADER:
  Name: "Wandering Trader"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

TURTLE:
  Name: "Turtle"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SLIME:
  Name: "Slime"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

COD:
  Name: "Cod"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

RAVAGER:
  Name: "Ravager"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

WITCH:
  Name: "Witch"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

GHAST:
  Name: "Ghast"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ZOMBIE_HORSE:
  Name: "Zombie Horse"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

WOLF:
  Name: "Wolf"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

VINDICATOR:
  Name: "Vindicator"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ZOGLIN:
  Name: "Zoglin"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

TRADER_LLAMA:
  Name: "LLama"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ZOMBIE_VILLAGER:
  Name: "Zombie Villager"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ENDER_DRAGON:
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

WITHER:
  Name: "Witch"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

VILLAGER:
  Name: "Villager"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

PARROT:
  Name: "Parrot"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

TROPICAL_FISH:
  Name: "Tropical Fish"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

VEX:
  Name: "Vex"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ZOMBIFIED_PIGLIN:
  Name: "Zombified Piglin"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

MAGMA_CUBE:
  Name: "Panda"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

PANDA:
  Name: "Panda"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SNOW_GOLEM:
  Name: "Snow Golem"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

RABBIT:
  Name: "Rabbit"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

ALLAY:
  Name: "Allay"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

TADPOLE:
  Name: "Tadpole"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

FROG:
  Name: "Frog"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

WARDEN:
  Name: "Warden"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

CAMEL:
  Name: "Camel"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"

SNIFFER:
  Name: "Sniffer"
  Drop: true
  Chance: 100
  Lore:
    - "Killed by {KILLER}"
    - "Killed on {DATE}"


