# Head Drop by RRS
# join support server: https://discord.gg/EWH5PhaCuh 

config:
    version: 1.8 #don't edit or plugin may break
    update-checker: true 
    
message:
    myhead: "%player%'s head added on your inventory."
    head: "%player%'s head added on your inventory."

Drop:
    Player: true 
    Cave_spider: true 
    Blaze: true 
    Chicken: true 
    Cow: true 
    Enderman: true 
    Ghast: true 
    Magma: true 
    Mushroom_Cow: true 
    Sheep: true 
    Slime: true 
    Squid: true 
    Villager: true 
    Golem: true 
    Ocelot: true 
    Pig: true 
    Wither: true 
    Creeper: false 
    Bee: true 
    Evoker: true 
    Fox: true 
    Goat: true 
    Guardian: true 
    Husk: true 
    Parrot: true
    Rabbit: true 
    Strider: true 
    Turtle: true 
    Vex: true 
    Vindicator: true 
    Witch: true 
    Wolf: true 
    Zombie: false 
    Skeleton: false 
    Bat: true 
    Cat: true 
    Cod: true 
    Donkey: true 
    Horse: true 
    Mule: true 
    Piglin: true 
    Polar_Bear: true 
    Pufferfish: true 
    Salmon: true 
    Skeleton_Horse: true 
    Snow_Golem: true 
    Wandering_Trader: true 
    Dolphin: true 
    Llama: true 
    Panda: true 
    Spider: true
    Zombified_Piglin: true
    Drowned: true
    Elder_Guardian: true
    Endermite: true
    Hoglin: true
    Phantom: true 
    Axolotl: true 
    Glow_Squid: true 
    Stray: true  
    
Chance: #Drop Need to be enable
    Players: 100
    CaveSpider: 100
    Blaze: 100
    Chicken: 100
    Cow: 100
    Enderman: 100
    Ghast: 100
    MagmaCube: 100
    MushroomCow: 100
    Sheep: 100
    Slime: 100
    Villager: 100
    IronGolem: 100
    Ocelot: 100
    Pig: 100
    Wither: 100
    Creeper: 100
    Bee: 100
    Evoker: 100
    Fox: 100
    Goat: 100
    Guardian: 100
    Husk: 100
    Parrot: 100
    Rabbit: 100
    Shulker: 100
    Strider: 100
    Turtle: 100
    Vex: 100
    Vindicator: 100
    Zombie: 100
    Skeleton: 100
    Bat: 100
    Cat: 100
    Cod: 100
    Donkey: 100
    Horse: 100
    Mule: 100
    Piglin: 100
    PolarBear: 100
    PufferFish: 100
    Salmon: 100
    SkeletonHorse: 100
    SnowGolem: 100
    WanderingTrader: 100
    Dolphin: 100
    Llama: 100
    Panda: 100
    Drowned: 100
    ZombifiedPiglin: 100
    Spider: 100
    ElderGuardian: 100
    Endermite: 100
    Hoglin: 100
    Phantom: 100
    Axolotl: 100
    GlowSquid: 100
    Stray: 100
    Witch: 100
    Squid: 100